[package]
name = "rmk-klor"
version = "0.1.0"
description = "RMK firmware for the Klor split keyboard"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
cortex-m-rt = "0.7"
defmt = "1"
embassy-executor = { version = "0.10", features = ["platform-cortex-m", "executor-thread"] }
embassy-rp = { version = "0.10", features = ["rp2040", "time-driver", "critical-section-impl"] }
embassy-time = "0.5"
panic-probe = "1"
portable-atomic = { version = "1", features = ["critical-section"] }
rmk = { version = "0.9", default-features = false, features = ["storage", "vial", "watchdog", "split", "rp2040", "ssd1306"] }
static_cell = "2"

[build-dependencies]
const-gen = "1.6"
json = "0.12"
xz2 = "0.1.7"

[[bin]]
name = "central"
path = "src/central.rs"
test = false
bench = false

[[bin]]
name = "peripheral"
path = "src/peripheral.rs"
test = false
bench = false

[profile.release]
codegen-units = 1
debug = false
opt-level = "z"
overflow-checks = false
lto = "fat"
