[keyboard]
name = "rmk-klor"
product_name = "rmk-klor"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
chip = "rp2040"

[layout]
rows = 4
cols = 12
layers = 1
keymap = [
    [
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    ],
]

[storage]

[split]
connection = "serial"

[split.central]
rows = 4
cols = 6
row_offset = 0
col_offset = 0
serial = [
    { instance = "PIO0", tx_pin = "PIN_0", rx_pin = "PIN_4" },
]
[split.central.matrix]
matrix_type = "normal"
input_pins = ["PIN_5", "PIN_6", "PIN_7", "PIN_8"] # rows
output_pins = ["PIN_27", "PIN_26", "PIN_22", "PIN_20", "PIN_23", "PIN_21"] # cols

[[split.peripheral]]
rows = 4
cols = 6
row_offset = 0
col_offset = 6
serial = [{ instance = "PIO0", tx_pin = "PIN_0", rx_pin = "PIN_4" }]
[split.peripheral.matrix]
matrix_type = "normal"
input_pins = ["PIN_5", "PIN_6", "PIN_7", "PIN_8"] # rows
output_pins = ["PIN_27", "PIN_26", "PIN_22", "PIN_20", "PIN_23", "PIN_21"] # cols
