[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP2040"

[build]
target = "thumbv6m-none-eabi"

[env]
KEYBOARD_TOML_PATH =  { value = "keyboard.toml", relative = true }
